### ISSUE TITLE
Only 12 articles are fetched

### ISSUE THREAD

**Issue by nicosomb** [FaustXVI/poche-to-calibre#6]
Hello!
I updated the recipe with the last version. 
I use poche with poche hosting. 

Calibre downloads only 12 articles. 

What can be the problem?

**Comment by FaustXVI** [comment]
Hello,
the line `max_articles_per_feed = 15` allows calibre to download 15 articles, can you try to raise this value to 30 and see if it downloads more articles ? If it works, then the point may be our way to count, if not, the point is at fetch time.
Thanks for your help.

**Comment by nicosomb** [comment]
29 fetched articles.

**Comment by FaustXVI** [comment]
Hi. I refactor a lot of code lately and I think you problem may have disappeared but I can't reproduce on my workstation. Can you please check the result ?

**Comment by nicosomb** [comment]
Default configuration: 12 fetched articles. 
When I want 20 articles, I've got 15 articles. 
When I want 30 articles, error : 

```
Récupérer des informations de Poche
Resolved conversion options
calibre version: 1.19.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': None,
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_download_recipe': False,
 'dont_split_on_page_breaks': True,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': None,
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x3503690>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0,
 'linearize_tables': False,
 'lrf': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x3503a90>,
 'page_breaks_before': None,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': None,
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': None,
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': '',
 'sr1_search': '',
 'sr2_replace': '',
 'sr2_search': '',
 'sr3_replace': '',
 'sr3_search': '',
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'test': False,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: Recipe Input running
Using custom recipe
Traceback (most recent call last):
  File "site.py", line 58, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 192, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1035, in run
  File "site-packages/calibre/customize/conversion.py", line 241, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/recipe_input.py", line 117, in convert
  File "site-packages/calibre/web/feeds/news.py", line 982, in download
  File "site-packages/calibre/web/feeds/news.py", line 1147, in build_index
  File "<string>", line 41, in parse_index
  File "<string>", line 93, in parse
  File "<string>", line 131, in get_contents_key
  File "site-packages/calibre/web/feeds/news.py", line 652, in index_to_soup
  File "site-packages/mechanize/_mechanize.py", line 199, in open_novisit
  File "site-packages/mechanize/_mechanize.py", line 255, in _mech_open
httperror_seek_wrapper: HTTP Error 403: Forbidden
```

**Comment by FaustXVI** [comment]
Your 403 error is due to the new table of content ( see #4 ). The root of on of your feeds seams to need a login and a password, it's unrelated with your issue (but I take note). It seems that the script doesn't know how to count… Do you think there is any thing strange in your feeds ?

**Comment by nicosomb** [comment]
I sent to you my RSS feed.
